-- EcoCollect - PostgreSQL schema (converted from the MySQL 5.x dump)
--
-- Dialect notes on this conversion:
--   * int(11) AUTO_INCREMENT  -> integer GENERATED BY DEFAULT AS IDENTITY
--   * tinyint(1)             -> boolean
--   * enum(...)              -> text + CHECK constraint (easier to alter later)
--   * timestamp              -> timestamptz (MySQL DATETIME has no zone; we store UTC)
--   * ON UPDATE CURRENT_TIMESTAMP -> no direct equivalent, so a trigger sets it
--   * decimal(10,2)          -> numeric(10,2)
--   * MySQL stored every timestamp in the server's local zone. TIMESTAMPTZ here
--     stores an absolute instant, so reports group by UTC day unless the column
--     is cast. collection_date / collection_time are kept as DATE / TIME because
--     "which day did this collection happen" is a local-calendar question.

DROP TABLE IF EXISTS collections CASCADE;
DROP TABLE IF EXISTS schedules CASCADE;
DROP TABLE IF EXISTS dumping_reports CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS collectors CASCADE;
DROP TABLE IF EXISTS barangays CASCADE;
DROP TABLE IF EXISTS settings CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS login_attempts CASCADE;
DROP TABLE IF EXISTS login_events CASCADE;

CREATE TABLE users (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username    varchar(50)  NOT NULL UNIQUE,
  -- bcrypt. PHP produced $2y$ hashes; bcryptjs verifies those unchanged.
  password    varchar(255) NOT NULL,
  full_name   varchar(100) NOT NULL,
  role        text NOT NULL DEFAULT 'collector'
              CHECK (role IN ('admin', 'collector', 'supervisor')),
  contact     varchar(20),
  email       varchar(100),
  is_active   boolean NOT NULL DEFAULT true,
  -- Set on seeded/demo accounts, whose password is published in the README. The
  -- app refuses to do anything else until it is cleared, so a deployment that
  -- forgot to change the default cannot quietly keep using it.
  must_change_password boolean NOT NULL DEFAULT false,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE collectors (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id       integer NOT NULL UNIQUE
                REFERENCES users (id) ON DELETE CASCADE,
  employee_id   varchar(50) UNIQUE,
  route         varchar(100),
  vehicle_type  varchar(50),
  vehicle_plate varchar(20),
  is_active     boolean NOT NULL DEFAULT true,
  created_at    timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE barangays (
  id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        varchar(100) NOT NULL,
  population  integer NOT NULL DEFAULT 0,
  zone        varchar(50),
  address     text,
  qr_code     varchar(255) NOT NULL UNIQUE,
  latitude    numeric(10,8),
  longitude   numeric(11,8),
  is_active   boolean NOT NULL DEFAULT true,
  created_at  timestamptz NOT NULL DEFAULT now(),
  updated_at  timestamptz NOT NULL DEFAULT now()
);

-- Table order matters here. Postgres validates a foreign key's target immediately,
-- unlike the MySQL dump which could defer checks with SET FOREIGN_KEY_CHECKS=0.
-- So schedules is created before collections, because collections.schedule_id
-- points at it.
CREATE TABLE schedules (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  barangay_id   integer NOT NULL REFERENCES barangays (id) ON DELETE CASCADE,
  collector_id  integer REFERENCES collectors (id) ON DELETE SET NULL,
  day_of_week   text NOT NULL
                CHECK (day_of_week IN ('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday')),
  time_start    time NOT NULL DEFAULT '06:00',
  time_end      time NOT NULL DEFAULT '12:00',
  route_name    varchar(100),
  is_active     boolean NOT NULL DEFAULT true,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_schedules_barangay ON schedules (barangay_id);

CREATE TABLE collections (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  barangay_id     integer NOT NULL REFERENCES barangays (id) ON DELETE CASCADE,
  collector_id    integer NOT NULL REFERENCES collectors (id) ON DELETE CASCADE,
  schedule_id     integer REFERENCES schedules (id) ON DELETE SET NULL,
  weight_kg       numeric(10,2) NOT NULL DEFAULT 0,
  waste_type      text NOT NULL DEFAULT 'Mixed'
                  CHECK (waste_type IN ('Organic','Plastic','Residual','Recyclable','Hazardous','Mixed')),
  bags_count      integer NOT NULL DEFAULT 0,
  photo           text,
  notes           text,
  latitude        numeric(10,8),
  longitude       numeric(11,8),
  collection_date date   NOT NULL,
  -- Stored as TIME (wall clock, no zone) exactly as MySQL did. The original code
  -- wrote date('Y-m-d') + date('H:i:s') from the PHP process, so TIME is the
  -- faithful representation and avoids a timezone shift in printed schedules.
  collection_time time NOT NULL,
  status          text NOT NULL DEFAULT 'completed'
                  CHECK (status IN ('completed','partial','missed')),
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_collections_barangay  ON collections (barangay_id);
CREATE INDEX idx_collections_collector ON collections (collector_id);
CREATE INDEX idx_collections_date      ON collections (collection_date);

CREATE TABLE dumping_reports (
  id              integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_name   varchar(100),
  reporter_contact varchar(20),
  barangay_id     integer REFERENCES barangays (id) ON DELETE SET NULL,
  description     text NOT NULL,
  photo           text,
  latitude        numeric(10,8),
  longitude       numeric(11,8),
  address         text,
  status          text NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending','verified','resolved','dismissed')),
  admin_notes     text,
  reported_at     timestamptz NOT NULL DEFAULT now(),
  resolved_at     timestamptz
);

CREATE TABLE notifications (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title         varchar(200) NOT NULL,
  message       text NOT NULL,
  type          text NOT NULL DEFAULT 'info'
                CHECK (type IN ('missed_collection','alert','info','dumping_report','message')),
  is_read       boolean NOT NULL DEFAULT false,
  is_archived   boolean NOT NULL DEFAULT false,
  related_id    integer,
  related_type  varchar(50),
  sender_id     integer,
  -- NULL means "broadcast to all admins", matching the original schema comment.
  recipient_id  integer,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_notifications_inbox ON notifications (is_archived, created_at DESC);

CREATE TABLE settings (
  id            integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  setting_key   varchar(100) NOT NULL UNIQUE,
  setting_value text,
  updated_at    timestamptz NOT NULL DEFAULT now()
);

-- Brute-force throttle. Serverless functions have no reliable in-memory store and
-- no writable disk, so attempt counters live in the database keyed by an HMAC of
-- IP + user agent. Hashing keeps raw IPs out of the table.
--
-- One row is written per failed attempt and carries both throttle scopes, so the
-- per-network and per-account counters can never drift apart:
--   client_key   HMAC(ip + user agent) - stops one host spraying many accounts
--   username_key HMAC(lower(username)) - stops many hosts attacking one account
CREATE TABLE login_attempts (
  id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  client_key   text NOT NULL,
  username_key text NOT NULL DEFAULT '',
  succeeded_at timestamptz NOT NULL DEFAULT now(),
  ip_hash      text
);
CREATE INDEX idx_login_attempts_key ON login_attempts (client_key, succeeded_at DESC);
CREATE INDEX idx_login_attempts_user ON login_attempts (username_key, succeeded_at DESC)
  WHERE username_key <> '';

-- Login audit trail. Records every attempt, successful or not, so "who signed in
-- from where and when" is answerable after the fact. The address is stored as a
-- truncated HMAC rather than in the clear, matching login_attempts; the username
-- is kept verbatim because the log cannot answer its question without it.
CREATE TABLE login_events (
  id         integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username   varchar(50) NOT NULL DEFAULT '',
  success    boolean NOT NULL DEFAULT false,
  reason     varchar(40) NOT NULL DEFAULT '',
  ip_hash    text,
  user_agent varchar(120),
  created_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_login_events_recent ON login_events (created_at DESC);
-- Failed attempts are the ones anyone queries when investigating; index the
-- subset rather than the whole table.
CREATE INDEX idx_login_events_failures ON login_events (username, created_at DESC)
  WHERE success = false;

-- Preserve MySQL's ON UPDATE CURRENT_TIMESTAMP behaviour.
CREATE OR REPLACE FUNCTION touch_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER trg_barangays_updated_at BEFORE UPDATE ON barangays
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();
CREATE TRIGGER trg_settings_updated_at BEFORE UPDATE ON settings
  FOR EACH ROW EXECUTE FUNCTION touch_updated_at();

-- The MySQL database had collected plaintext passwords in this table because the
-- old settings handler persisted every POST field it did not recognise. Names are
-- blocked here as a hard backstop so that can never recur.
CREATE OR REPLACE FUNCTION guard_setting_key() RETURNS trigger AS $$
BEGIN
  IF NEW.setting_key ~* '(password|secret|token|csrf|api[_-]?key)' THEN
    RAISE EXCEPTION 'refusing to store a secret-like setting key: %', NEW.setting_key;
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_settings_no_secrets BEFORE INSERT OR UPDATE ON settings
  FOR EACH ROW EXECUTE FUNCTION guard_setting_key();
